server:
    port: 5346
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            route:
                - id: dump-service
                  uri: lb://DUMP-SERVICE
                  predicates:
                    - Path=/dump/**
            discovery:
                locator:
                    enabled: true
management:
    endpoints:
        web:
            exposure:
                include: '*'