server:
    port: 5346
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
#            defaultZone: http://host.docker.internal:8761/eureka
spring:
    application:
        name: api-gateway
    cloud:
        discovery:
            enabled: true
        load-balance:
            ribbon:
                enable: false
        gateway:
            logging:
                level:
                    org.springframework.cloud.gateway: TRACE
                    reactor.netty.http.client: TRACE
            discovery:
                locator:
                    enabled: true
            global cors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "http://localhost:3000"
                        allowedHeaders: "*"
                        allowedMethods: "*"
                preflight:
                    pass through:true
#            routes:
#                - id: user_route
#                  uri: lb://user-service
#                  predicates:
#                      - Path=/user-service/**
#                  filters:
#                      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
management:
    endpoints:
        web:
            exposure:
                include: '*'